[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32L476RG ./target/thumbv7em-none-eabihf/debug/main"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
b_stm32 = "build --target=thumbv7em-none-eabihf"
test_a = "test --all --target=x86_64-unknown-linux-gnu -- --nocapture"
